### ISSUE TITLE
No config options, fix in readme not working

### ISSUE THREAD

**Issue by jonseppanen** [nclarius/tile-gaps#6] opened 2022-01-28 04:53 UTC
As stated, latest arch/endeavour

No config options, even when applying the fix in readme.

**Comment by nclarius** [comment] 2022-01-28 05:34
Even after logging out and in again?

**Comment by jonseppanen** [comment] 2022-01-28 05:36
After logout it shows up but says "Plugin does not provide configuration file in expected location" when clicked.

**Comment by nclarius** [comment] 2022-01-28 06:56
That's strange.

  Do the flowing files exist?
 `~/.local/share/kwin/scripts/tilegaps/contents/config/main.xml`  
 `~/.local/share/kwin/scripts/tilegaps/contents/confi.ui`  
`~/.config/kwinrc`

**Comment by nclarius** [comment] 2022-01-28 17:41
Looks like https://bugs.kde.org/show_bug.cgi?id=444378 https://forum.garudalinux.org/t/bismuth-settings-fail/13236.

**Comment by nclarius** [comment] 2022-01-31 21:05
While the problem persists, a workaround might be to edit the configuration directly:

In `~/.config/kwinrc`, overwrite or else append:
```
[Script-tilegaps]
gapTop=12
gapLeft=12
gapRight=12
gapBottom=12
gapMid=12
includeMaximized=false
excludeMode=true
excludedApps=
includeMode=false
includedApps=
```

**Comment by nclarius** [comment] 2022-02-13 20:34
With 5.24 I am now experiencing the same problem. There is currently no working fix that I know of.

**Comment by nclarius** [comment] 2022-03-21 20:06
This issue has been fixed in KWin now, so I assume the problem is solved. If not, please reopen.

**Closed by nclarius** 2022-03-21 20:06 UTC
Labels: bug
